### ISSUE TITLE
JS: 增加各插件使用 js 调用、控制的例子

### ISSUE THREAD

**Issue by Minwe** [allmobilize/amazeui#132]
> 我发现你很多实例都是要我们用鼠标去点的 而不是JS控制的
  希望多点例子是用JS控制切换或者模拟点击的 因为很多时候我们程序要实现接参数模拟点击的

**Comment by lndj** [comment]
请问我在折叠面板上嵌套表格，为什么折叠的标题会变得很宽？能不能收收....

**Comment by Minwe** [comment]
宽是什么意思？表格多宽，标题就有多宽啊。最好贴出实际例子。

**Comment by lndj** [comment]
请看看http://lndj.github.io/

**Comment by Minwe** [comment]
`.am-table` 有 `1.6rem` 的下边距，单元格有 `.7rem` 的内边距，所以就高了。使用框架不能代替你学习 HTML、CSS 基础知识，建议先去看一些基础知识，最起码知道如何查找定位问题。

这种场合不建议使用 `table`，如果你不会其他方式实现左右的布局，那就把 `am-table` 这个 class 移除，就不会那么高了。

```css
.am-table {
  width: 100%;
  margin-bottom: 1.6rem;
  border-spacing: 0;
  border-collapse: separate;
}

.am-table>thead>tr>th, .am-table>tbody>tr>th, .am-table>tfoot>tr>th, .am-table>thead>tr>td, .am-table>tbody>tr>td, .am-table>tfoot>tr>td {
  padding: .7rem;
  line-height: 1.6;
  vertical-align: top;
  border-top: 1px solid #DDD;
}
```
