### ISSUE TITLE
等分网格嵌套在网格中，ul/ol的高度出现错误

### ISSUE THREAD

**Issue by qetee** [allmobilize/amazeui#340]
代码结构
```html
div.am-g.am-g-fixed
    div.am-u-sm-2
        ...
    div.am-u-sm-10
        ul.am-avg-md-2
            li ...
            li ...
```

此时出现错误，如图
![qq 20141220052305](https://cloud.githubusercontent.com/assets/2811986/5511424/53b2b7c6-8808-11e4-9c2a-8c5c785ec00c.png)

无缘无故的高度，在firebug里，看不到任何对高度的定义

在css里加入如下代码后，错误得到修复
```css
.am-u-sm-10  *, 
.am-u-sm-10 *:after, 
.am-u-sm-10 *:before { 
    clear:none;
}
```
![qq 20141220052733](https://cloud.githubusercontent.com/assets/2811986/5511472/efd7d938-8808-11e4-8d96-3d63813bf0d1.png)
