### ISSUE TITLE
rem单位在Firefox和Chrome下大小不一致……

### ISSUE THREAD

**Issue by PonyC** [allmobilize/amazeui#544]
同样的代码，用rem设置长款，火狐和chrome的大小差40PX，font-size都是16啊
这个是什么原因？

**Comment by Minwe** [comment]
你可以先不引入 Amaze UI 的样式，测试一下这两个浏览器上是否有差别。

**Comment by PonyC** [comment]
不引用大小是一样的，引用后就不一样了~~

**Comment by Minwe** [comment]
http://bin.amazeui.org/qukoca/1/edit?html,console

不引入也不一样，Firefox 的默认字号是 `15px`，Chrome 的默认字号是 `16px`。

```css
      html {
        font-size: 62.5%;
      }

      body {
        font-size: 1.6rem;
      }

      #test {
        width: 50rem;
        border: 1px solid red;
        height: 10rem;
      }
```

所以 `div` 的宽度就是：

- Chrome：16 * 62.5% * 50 = 500px
- Firefox: 15 * 62.5% * 50 = 469.167px

要一致的话就把 html 的字号设置为 `10px`：

```css
      html {
        font-size: 10px;
      }
```
