### ISSUE TITLE
Bug: 取消Firefox下拉选框的默认样式

### ISSUE THREAD

**Issue by photino** [allmobilize/amazeui#556]
![firefox](https://cloud.githubusercontent.com/assets/3446306/7553388/5eb6b8d6-f728-11e4-8949-e18885daf58e.png)

由于AmazeUI对`<select>`元素设置了SVG格式的背景图片，所以同样需要取消Firefox的默认格式：
```css
select {
  -moz-appearance: none;
  -webkit-appearance: none;
  appearance: none;
}
```
Firefox 35+已经支持`-moz-appearance`，希望AmazeUI能够修正一下上面截图中同时显示两个下三角形的问题（在Ubuntu 14.04系统Firefox 37中测试）。
