### ISSUE TITLE
增加一些消除 margin/padding 的辅助类

### ISSUE THREAD

**Issue by Tobyee** [allmobilize/amazeui#565]
某些场景下需要去掉 margin，如果下图，在一个 panel里放一个 form ，由于 panel 本身有 padding，所以 form 的最后一个 form-group 需要去掉 margin-bottom 才完美。

![default](https://cloud.githubusercontent.com/assets/1400574/7702145/95fa9666-fe60-11e4-8e9b-b6d2b146c27f.png)

当然去掉的方案有很多：
1、把这些场景都挑出来统一处理，例如
````css
.am-panel-bd >.am-form>.am-form-group:last-child {
    margin-bottom:0;
}
````
2、在自定义样式针对性处理
3、增加一些消除 margin 的辅助类，例如
````css
.am-margin-none {
    margin:0;
}
.am-margin-top-none...
.am-margin-bottom-none...
````

个人偏向方案三，同理 padding 也可以增加类似的辅助类，这些辅助类用于消除 amazeui 已定义好的 margin / padding 非常有用。
