### ISSUE TITLE
对于没有 thead 的 table 上边框会重复

### ISSUE THREAD

**Issue by Tobyee** [allmobilize/amazeui#566]
http://bin.amazeui.org/zopuzerika/1/edit

**Comment by Minwe** [comment]
略长：

```css
.am-table-bordered > tbody > tr:first-child > th,
.am-table-bordered > tbody > tr:first-child > td {
  border-top: none;
}
.am-table-bordered > thead + tbody > tr:first-child > th,
.am-table-bordered > thead + tbody > tr:first-child > td {
  border-top: 1px solid #dddddd;
}
```
